backend:
  name: github
  repo: kingsleysqi/astro-blog-starter-template  # 修正了用户名和仓库名
  branch: main
  base_url: https://cool-forest-c1b4.kingsley-s-qi.workers.dev
  auth_endpoint: auth

media_folder: "public"
public_folder: "/"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Pub Date", name: "pubDate", widget: "datetime" }
      - { label: "Hero Image", name: "heroImage", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
